music/urls.py
from django.contrib import admin
from django.urls import path
from music import views

app_name="music"

urlpatterns = [
    path('',views.home,name='home'),
    path('artist/<str:a>/', views.artist, name='artist'),
    path('albums/<str:a>/', views.albums, name='albums'),
    path('songs/<str:a>/', views.songs, name='songs'),
    #path('play/<str:a>/', views.play, name='play'),

    path('play/<int:a>/', views.play, name='play'),

    path('register', views.register, name='register'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name="logout"),




    path('playlist', views.playlist, name='playlist'),


    path('add_to_playlist/<int:a>/', views.add_to_playlist, name='add_to_playlist'),

    path('playlist_remove/<p>',views.playlist_remove,name="playlist_remove"),

    path('shuffle', views.shuffle, name='shuffle'),

    path('all_artists/', views.all_artists, name='all_artists'),
    path('all_albums/', views.all_albums, name='all_albums'),



    #path('add_to_playlist/<int:song_id>/', views.add_to_playlist, name='add_to_playlist'),





]

musicsite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls')),

    path('search/', include('search.urls')),
    path('mysub/', include('mysub.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Genre(models.Model):
    g_name = models.CharField(max_length=50)
    g_photo = models.ImageField(upload_to='media/genre_photos/', null=True, blank=True)
    g_description = models.TextField()

    def __str__(self):
        return self. g_name

class Artist(models.Model):
    Artist_name = models.CharField(max_length=100)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    Artist_photo = models.ImageField(upload_to='media/artist_photos/', null=True, blank=True)
    Artist_description = models.TextField()

    def __str__(self):
        return self.Artist_name

class Album(models.Model):
    Album_title = models.CharField(max_length=100)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    Album_price = models.DecimalField(max_digits=10, decimal_places=2)
    Album_photo = models.ImageField(upload_to='media/album_photos/', null=True, blank=True)
    Album_description = models.TextField()

    def __str__(self):
        return self.Album_title

class Song(models.Model):
    Song_title = models.CharField(max_length=100, default='Untitled')
    album = models.ForeignKey(Album, on_delete=models.CASCADE, default=1)
    file = models.FileField(upload_to='media/songs/', null=True, blank=True)

    def __str__(self):
        return self.Song_title



class Playlist(models.Model):
    song=models.ForeignKey(Song,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    number = models.IntegerField(null=True, blank=True)
    date_added=models.DateField(auto_now_add=True)

music/views.py
from django.shortcuts import render,redirect
from music.models import Genre,Artist,Album,Song,Playlist
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
import random
from mysub.models import Account,Subscribe
from django.core.exceptions import ObjectDoesNotExist



# Create your views here.

def home(request):
    genres = Genre.objects.all()
    albums = Album.objects.all()
    artists = Artist.objects.all()
    songs = Song.objects.all()

    shuffled_artists = list(artists)
    shuffled_songs = list(songs)
    shuffled_trends = list(albums)


    random.shuffle(shuffled_artists)
    random.shuffle(shuffled_songs)
    random.shuffle(shuffled_trends)

    return render(request, 'music/home.html', {'genres': genres,
                                               'artists': shuffled_artists[:3],
                                               'songs': shuffled_songs[:1],
                                               'trends': shuffled_trends[:3]})


@login_required
def artist(request, a):
    # Filter artists based on the genre name
    b = Artist.objects.filter(genre__g_name=a)

    # Retrieve the genre object
    genre = Genre.objects.get(g_name=a)
    return render(request, 'music/artist.html', {'b': b, 'genre': genre})


@login_required
def albums(request, a):

    # Filter albums based on the artist name
    al = Album.objects.filter(artist__Artist_name=a)

    # Retrieve the artist object
    artist = Artist.objects.get(Artist_name=a)

    return render(request, 'music/albums.html', {'albums': al, 'artist': artist})





@login_required
def songs(request, a):

    # Filter songs based on the album title
    songs = Song.objects.filter(album__Album_title=a)

    album = Album.objects.get(Album_title=a)

    return render(request, 'music/songs.html', {'songs': songs, 'album': album})




# #this is for playing songs
# def play(request,a):
#     song=Song.objects.get(pk=a)
#     return render(request, 'music/play.html', {'song': song})



@login_required
def play(request, a):
    user = request.user

    try:
        s = Subscribe.objects.get(user=user)
    except ObjectDoesNotExist:
        # Redirect the user to the subscribe page when Subscribe object does not exist
        return redirect('mysub:sub')

    if s :
        song = Song.objects.get( pk=a)

        # Get the album and all songs in that album
        album = song.album
        all_songs = list(album.song_set.all())  # Convert  to a list

        # Find the index of the current song in the list of all songs
        current_song_index = all_songs.index(song)

        # Calculate the index of the previous and next songs
        previous_song_index = (current_song_index - 1) % len(all_songs)
        next_song_index = (current_song_index + 1) % len(all_songs)

        # Get the previous and next songs
        previous_song = all_songs[previous_song_index]
        next_song = all_songs[next_song_index]

        return render(request, 'music/play.html', {
            'song': song,
            'previous_song': previous_song,
            'next_song': next_song,
        })











def playlist(request):
    if request.user.is_authenticated:
        # Retrieve the user's playlist entries
        user_playlist = Playlist.objects.filter(user=request.user)
        return render(request, 'music/playlist.html', {'playlist': user_playlist})
    else:
        # when the user is not authenticated
        return redirect('music:login')



def add_to_playlist(request, a):

    song = Song.objects.get(pk=a)

    # Check if the song is already in the user's playlist
    if Playlist.objects.filter(user=request.user, song=song).exists():
        pass
    else:
        # Add the song to the playlist
        Playlist.objects.create(user=request.user, song=song)

    return playlist(request)    #changed as favts




def playlist_remove(request, p):

    playlist_entry = Playlist.objects.get (pk=p)

    # Check if the user making the request is the owner of the playlist entry
    if request.user == playlist_entry.user:
        # Delete the playlist entry
        playlist_entry.delete()

    else:
       pass
    return redirect('music:playlist')



# def all_artists(request):
#     # Get all artists ordered alphabetically
#     artists = Artist.objects.all().order_by('Artist_name')
#     return render(request, 'music/all_artists.html', {'artists': artists})



def all_artists(request):

    # Get all artists ordered alphabetically
    artists = Artist.objects.all().order_by('Artist_name')

    # Create a dictionary to group artists by the first letter of their name
    grouped_artists = {}
    for artist in artists:
        first_letter = artist.Artist_name[0].upper()
        if first_letter not in grouped_artists:
            grouped_artists[first_letter] = []
        grouped_artists[first_letter].append(artist)

    return render(request, 'music/all_artists.html', {'grouped_artists': grouped_artists})




def all_albums(request):

    # Get all albums ordered alphabetically
    albums = Album.objects.all().order_by('Album_title')

    # Create a dictionary to group albums by the first letter of their name
    grouped_albums = {}

    for album in albums:
        first_letter = album.Album_title[0].upper()
        if first_letter not in grouped_albums:
            grouped_albums[first_letter] = []

        grouped_albums[first_letter].append(album)

    return render(request, 'music/all_albums.html', {'grouped_albums': grouped_albums})





def register(request):
    if(request.method=="POST"):
        u = request.POST['u']
        p = request.POST['p']
        p1 = request.POST['p1']
        e = request.POST['e']
        f = request.POST['f']
        l = request.POST['l']
        if(p==p1):
            u=User.objects.create_user(username=u,password=p,email=e,first_name=f,last_name=l)
            u.save()
            return redirect('music:home')

    return render(request,'music/register.html')


def user_login(request):
    if (request.method == "POST"):
        u = (request.POST['u'])
        p = (request.POST['p'])
        user = authenticate(username=u, password=p)

        if user:
            login(request,user)
            return redirect('music:home')
        else:
            messages.error(request, "invalid credentails")
    return render(request,'music/login.html')


def user_logout(request):
    logout(request)
    return user_login(request)


def shuffle(request):
    songs = Song.objects.all()
    shuffled_songs = list(songs)
    random.shuffle(shuffled_songs)
    return render(request,'music/shuffle.html',{'songs':shuffled_songs[:1]})

templates/music/albums.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<style>
    body {
        font-family: 'Arial', sans-serif;
        color: #333;
        margin: 0;
        padding: 0;
    }

    h1 {
        text-align: center;
        color: #2c3e50;
    }

    .song-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-around;
        margin: 20px;
    }

    .song-card {
        width: 14rem;  /* Adjusted width */
        margin: 10px;
        padding: 20px;
        border: 2px solid #3498db;
        border-radius: 8px;
        background-color: #2c3e50;
        text-align: center;
    }

    h5 {
        color: white;
    }

    .play-link {
        display: block;
        margin-top: 10px;
        padding: 10px;
        background-color: #3498db;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        transition: background-color 0.3s;
    }

    .play-link:hover {
        background-color: #2980b9;
    }
</style>

<h1>Albums Collection</h1>
<center> <h2>Explore {{ artist.Artist_name }} Albums</h2> </center>
<center>
<div data-aos="zoom-in" class="row">
    {% for album in albums %}
        <div class="col-4">
            <div class="card song-card">

                {% if album.Album_photo %}

                    <img src="{{ album.Album_photo.url }}" class="card-img-top">

                {% else %}

                    <div class="placeholder-image"></div>

                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ album.Album_title }}</h5>
                    <p class="card-description">{{ album.Album_description }}</p>
                    <a href="{% url 'music:songs' album.Album_title %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/music/all_albums.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<style>
    .custom-card-size {
        width: 16rem;
    }


     body {
    background-image: url('{% static 'images/de1.jpg' %}');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: fixed;
}

</style>

<div class="container mt-5">
    <h1 class="mb-4">Complete Album Collection</h1>

    {% for letter, albums in grouped_albums.items %}
        <h2>{{ letter }}</h2>

        <div  data-aos="fade-right"
     data-aos-offset="100"
     data-aos-easing="ease-in-sine" class="row">

            {% for album in albums %}
                <div class="col-md-3 mb-5 custom-card-size">
                    <div class="card">
                        {% if album.Album_photo %}
                            <img src="{{ album.Album_photo.url }}" class="card-img-top">
                        {% else %}
                            <div class="placeholder-image"></div>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title" style="color: black;">{{ album.Album_title }}</h5>
                            <a href="{% url 'music:songs' album.Album_title %}" class="btn btn-outline-primary">Explore</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}

</div>

{% endblock %}

templates/music/all_artists.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<style>
.custom-card-size {
    width: 16rem;}


 body {
    background-image: url('{% static 'images/de1.jpg' %}');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: fixed;
}



</style>

<div  class="container mt-5">
    <h1 class="mb-4">All Artists Collection</h1>

    {% for letter, artists in grouped_artists.items %}

        <h2>{{ letter }}</h2>

        <div  data-aos="fade-right"
     data-aos-offset="100"
     data-aos-easing="ease-in-sine"  class="row">

            {% for i in artists %}
                <div  class="col-md-3 mb-5 custom-card-size">
                    <div class="card">
                        <img src="{{ i.Artist_photo.url }}" class="card-img-top">
                        <div class="card-body">
<!--                            <h5 class="card-title">{{ i.Artist_name }}</h5>-->


                             <a href="{% url 'music:albums' i.Artist_name %}" class="btn btn-outline-primary">Explore</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}

</div>

{% endblock %}

templates/music/artist.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    body {
        font-family: 'Arial', sans-serif;
        color: #333;
        margin: 0;
        padding: 0;
    }

    h1 {
        text-align: center;
        color: #2c3e50;
    }

    .artist-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-around;
        margin: 20px;
    }

    .artist-card {
        width: 12rem;  /* Adjusted width */
        margin: 10px;
        padding: 20px;
        border: 2px solid #3498db;
        border-radius: 8px;
        background-color: #2c3e50;
        text-align: center;
    }

    h5 {
        color: white;
    }

    .details-link {
        display: block;
        margin-top: 10px;
        padding: 10px;
        background-color: #3498db;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
        transition: background-color 0.3s;
    }

    .details-link:hover {
        background-color: #2980b9;
    }
</style>


<h1 class="text-center text-primary mb-4">Explore {{ genre.g_name }} Artist Collection</h1>

<div data-aos="fade-up"
     data-aos-duration="1000" class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4 artist-container">
        {% for artist in b %}
            <div class="col mb-4">
                <div class="card border rounded h-100 artist-card">
                    {% if artist.Artist_photo %}
                        <img src="{{ artist.Artist_photo.url }}" class="card-img-top img-fluid rounded">
                    {% else %}
                        <div class="placeholder-image"></div>
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title text-primary">{{ artist.Artist_name }}</h5>
                        <a href="{% url 'music:albums' artist.Artist_name %}" class="btn btn-outline-primary details-link">Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

templates/music/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}


<style>
    #audio-player {
    max-width: 300px;
    margin: 0 auto; /* Center the player on the page */
}

</style>


<div  data-aos="zoom-in-down" class="container mt-4">
    <h1 class="text-center mb-4">Welcome to Symphony Horizon {{ user.first_name }}</h1>


    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/b3o.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/b33.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/b55.png' %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>






    <div class="row">
        <!-- Genres -->
        <div
             class="col-md-6 mb-4">

            <h2 class="mb-3">Browse Genres</h2>
            <div data-aos="zoom-in"
     data-aos-easing="ease-out-cubic"
     data-aos-duration="2000" class="row row-cols-1 row-cols-md-2 g-4">
                {% for genre in genres %}
                    <div class="col mb-4">
                        <div class="card h-100 border-dark" style="background-color:grey">

                            <img src="{{ genre.g_photo.url }}" class="card-img-top" alt="{{ genre.g_name }}">

                            <div class="card-body">
                                <h5 style="color:black">{{ genre.g_name }}</h5>
                                <a href="{% url 'music:artist' genre.g_name %}" class="btn btn-outline-primary">Explore</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <!-- Featured Playlists -->
        <div class="col-md-6 mb-4">
            <h2 class="mb-3">Featured Playlists</h2>





             <!-- Artists -->
            <div class="scroll-box border p-3 mt-4">
                <h2 class="mt-4">Trending Artists</h2>
                <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
                    {% for artist in artists %}

                        <div data-aos="zoom-in"  class="col mb-4">

                            <div class="card h-100 border-dark">
                                <img src="{{ artist.Artist_photo.url }}" class="card-img-top" style="border-radius: 50%;">

                                <div class="card-body">
<!--                                    <h5 class="card-title text-danger">{{ artist.Artist_name }}</h5>-->
                                    <a href="{% url 'music:albums' artist.Artist_name %}" class="btn btn-outline-primary">Explore</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>


            <!-- Songs -->
            <div class="scroll-box border p-1 mt-2">
                <h2>Trending Songs</h2> <br>

                <center><div data-aos="flip-left">

                    {% for song in songs %}
                        <div  class="mb-4">
                            <div  id="audio-player" class="card">
                                <h4 class="card-title text-danger"> {{ song.Song_title }}</h4>
                                {% if song.album.Album_photo %}

                                    <img src="{{ song.album.Album_photo.url }}">
                                {% else %}

                                    <div class="placeholder-image"></div>

                                {% endif %}

                                <h6 class="card-subtitle text-info">Artist: {{ song.album.artist.Artist_name }}</h6>
                                <audio controls controlsList="nodownload">
                                    <source src="{{ song.file.url }}" type="audio/mp3">
                                    Your browser does not support the audio element.
                                </audio>
                            </div>
                           </div>
                       {% endfor %}
                    </div>
               </div>

             <!-- Trending Albums -->
<!--            <div class="scroll-box border p-3 mt-4">-->
                <h2>Trending Albums</h2>

                <div data-aos="zoom-in" class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">

                    {% for trend in trends %}
                        <div class="col mb-4">
                            <div class="card h-100 border-dark">
                                <img src="{{ trend.Album_photo.url }}" class="card-img-top" >
                                <div class="card-body">
                                    <h5 class="card-title text-danger">{{ trend.Album_title }}</h5>
                                    <a href="{% url 'music:songs' trend.Album_title %}"
                                       class="btn btn-primary"> Explore</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>




        </div>
    </div>
</div>

{% endblock %}

templates/music/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
    body {
        background-image: url('{% static 'images/de1.jpg' %}');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }



    h1, .form-label {
    color:#47b6ca }

    .loader_dot {
        display: inline-block;
        width: 15px;
        height: 15px;
        background-color: #47b6ca;
        opacity: 0.5;
        border-radius: 50%;
        animation: scale-up 1000ms var(--d) linear infinite;
    }

    @keyframes scale-up {
        25% {
            opacity: 1;
            transform: scale(1.5);
        }
        50% {
            transform: scale(1);
        }
    }
</style>


<form data-aos="fade-up" data-aos-anchor-placement="center-bottom" method="POST" class="myform">
    {% csrf_token %}

    <h1>Login here</h1>

    <div class="mb-3">
        <label class="form-label">Username</label>
        <input type="text" class="form-control" name="u" placeholder="Enter username">
    </div>

    <div class="mb-3">
        <label class="form-label">Password</label>
        <input type="password" class="form-control" name="p" placeholder="Enter password">
    </div>

    <div class="mb-3">
        <center>
            <input type="submit" class="attractive-btn" style="padding: 4px 70px;">
    </div>

    <center>
        <div class="loder">
            <span class="loader_dot" style="--d: 200ms"></span>
            <span class="loader_dot" style="--d: 400ms"></span>
            <span class="loader_dot" style="--d: 600ms"></span>
            <span class="loader_dot" style="--d: 800ms"></span>
            <span class="loader_dot" style="--d: 1000ms"></span>
        </div>
    </center>

</form>

{% if messages %}

<ul>
    {% for msg in messages %}
    <li>{{msg}}</li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}

templates/music/play.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<style>

    #audio-player {
    background-color:grey;
    max-width: 360px;
    opacity: 0.70;
    background-color: rgba(255, 255, 255, 0.2);
    transition: transform 0.3s, box-shadow 0.3s;

   }

   #audio-player {
    transform: scale(1.05); /* Scale up on hover */
    z-index: 2; }







</style>


    <center>
        <div class="box" data-aos="flip-left"
     data-aos-easing="ease-out-cubic"
     data-aos-duration="300"  >

        <div id="audio-player">
            <h5 style="color:red;">Now Playing: {{ song.Song_title }}</h5>

            {% if song.album.Album_photo %}
                <img src="{{ song.album.Album_photo.url }}" alt="{{ song.Song_title }}">
            {% else %}
                <div class="placeholder-image"></div>
            {% endif %}

            <audio controls controlsList="nodownload" autoplay>
                <source src="{{ song.file.url }}" type="audio/mp3">
                Your browser does not support the audio element.
            </audio>

            <a href="{% url 'music:play' previous_song.id %}"  class="backward"> Backward
            <i class="fas fa-backward" style="font-size: 24px; color: #3498db;"></i></a>


            <i class="fas fa-hand-spock" style="font-size: 24px; color: #3498db;"></i></a>

            <a href="{% url 'music:play' next_song.id %}" class="forward">
                <i class="fas fa-forward" style="font-size: 24px; color: #3498db;"></i> Forward</a>

            </div>
        </div>
    </center>
{% endblock %}

templates/music/playlist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="playlist-section">
        <style>
            .playlist-section {
                max-width: 800px;
                margin: 0 auto;
            }

            .playlist-section h1 {
                color: #2c3e50;
                margin-bottom: 20px;
            }



            .playlist-section li {
                border: 3px solid green;
                border-radius: 8px;
                background-color: #2c3e50;
                margin: 10px 0;
                padding: 20px;
                display: flex;
                justify-content: space-between;   /* gap between elemens */
                align-items: center;
                transition: background-color 0.3s;
            }

            .playlist-section li:hover {
                background-color: black;
            }

            .playlist-section .play-link {
                display: inline-block;
                padding: 10px;
                background-color: #3498db;
                color: #fff;

                border-radius: 5px;
                transition: background-color 0.3s;
            }

            .playlist-section .play-link:hover {
                background-color: red;
            }


        </style>

        <h1>Your Favourites</h1>

        {% if playlist %}
            <ul data-aos="zoom-out">
                {% for i in playlist %}
                    <li>
                        <span>{{ i.song.Song_title }}</span>
                        <a href="{% url 'music:playlist_remove' i.id %}" class="play-link">Remove</a>
                        <a href="{% url 'music:play' i.song.id %}" class="play-link">Play</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Your playlist is empty.</p>
        {% endif %}
    </div>
{% endblock %}

templates/music/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>

   .myform {
        max-width: 400px;
        margin: 0 auto;
    }

      body {
        background-image: url('{% static 'images/de1.jpg' %}');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }


</style>




<form  data-aos="zoom-in-up"

        method="POST" class="myform">
  {% csrf_token %}

<div style="margin:10px;">

<h1 style="color:#47b6ca">Register here</h1>
<div class="mb-3" ">
  <label  class="form-label" >Username</label>
  <input type="text" class="form-control" name="u" placeholder="Enter your username">
</div>

<div class="mb-3">
  <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="Enter your password">
</div>

<div class="mb-3">
  <label  class="form-label">Confirm Password</label>
  <input type="password" class="form-control" name="p1" placeholder="Confirm your password ">
</div>

<div class="mb-3">
  <label  class="form-label">First Name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter your first name">
</div>

<div class="mb-3">
  <label  class="form-label">Last Name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter your last name">
</div>

 <div class="mb-3">
  <label  class="form-label">Email</label>
  <input type="email" class="form-control" name="e" placeholder="Enter your e-mail address">
</div>


<div class="mb-3">
    <center>
    <input type="submit" class="attractive-btn" style="padding: 4px 70px;">
</div>

  </form>

</div>

{% endblock %}

templates/music/songs.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <style>
        body {
            font-family: 'Arial', sans-serif;
        }

        h1 {
            text-align: center;
            color: #2c3e50;
        }

        .song-container {
            display: flex;

            justify-content: space-around;
            margin: 20px;
        }

        .song-card {
            width: 300px;
            margin: 10px;
            padding: 20px;
            border: 2px solid #3498db;
            border-radius: 8px;
            background-color: #2c3e50;
            text-align: center;
        }

        h5 {
            color: white;
        }

        .play-link {
            display: block;
            margin-top: 10px;
            padding: 10px;
            background-color: #3498db;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .play-link:hover {
            background-color: #2980b9;
        }
    </style>
</head>
<body>
<center>
<h1>Songs in {{ album.Album_title }}</h1>

<div  data-aos="zoom-in-down" class="song-container">
    {% for i in songs %}
        <div class="song-card">
            <h5>{{ i.Song_title }}</h5>

            <a href="{% url 'music:play' i.id %}" class="play-link">
                 <i class="fas fa-play" style="color: white; font-size: 21px;"></i></a>

            <a href="{% url 'music:add_to_playlist' i.id %}" class="play-link">Add to favourites</a>

        </div>
    {% endfor %}
</div>

{% endblock %}